### ISSUE TITLE
Create server-side route + db function to edit an existing food

### ISSUE THREAD

**Issue by emilyparkes** [matai-2019/foodlist#16]
Create database function (`editFood(food)`) and server-side PUT route (`/api/v1/foods/:id`) to edit details of an existing food, as [described in the Wiki](https://github.com/matai-2019/foodlist/wiki/Server-Routes).

**Comment by LogansRuin** [comment]
- [x] route
- [x] function
- [x] test function
- [x] test route

**Comment by LogansRuin** [comment]
- [ ]

**Comment by iDeepDev8** [comment]
Currently blocked on testing the editFoods function. Getting a response from the test suite saying ```SQLITE_ERROR: no such table: foods```. This happens when the `editFood` function has run and tries to call the `getFood` function to deliver the response to the test suite.

**Comment by LogansRuin** [comment]
Unblocked: `editFood()` must pass down the `db` to `getFood()`
